name: Rust

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --all-features --all-targets
    - name: Lint
      run: cargo clippy --no-deps --all-features --all-targets -- --deny clippy::all
    - name: Run tests
      run: cargo test --all-features
    - name: Run doc tests
      run: cargo test --all-features --doc
    - name: Generate doc
      run: cargo doc --workspace --no-deps --all-features
